name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/checkout@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Build with Maven
              run: mvn clean install

            - name: Unit Test
              run: mvn test

            - name: Install git-secrets
              run: |
                 git clone https://github.com/awslabs/git-secrets.git
                 cd git-secrets && sudo make install
                 cd ..
            - name: Scan for secrets
              run: git secrets --scan -r

            - name: Generate JaCoCo coverage report
              run: mvn test jacoco:report

            - name: Upload JaCoCo report
              uses: actions/upload-artifact@v4
              with:
                  name: jacoco-report
                  path: target/site/jacoco

#             - name: SonarQube Scan
#               uses: sonarsource/sonarqube-scan-action@v2
#               with:
#                   projectBaseDir: .
#                   args: >
#                      -Dsonar.projectKey=your_project_key
#                      -Dsonar.organization=your_org
#                      -Dsonar.host.url=${{ secrets.SONAR_HOST_URL}}
#                      -Dsonar.login=${{secrets.SONAR_TOKEN}}


