name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/checkout@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Build with Maven
              run: mvn clean install

            - name: Unit Test
              run: mvn test
